//! Autogenerated weights for pallet_proofofface
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `proofofface-benchmarking`, CPU: `Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/proofofface-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_proofofface
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/proofofface/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_proofofface.
pub trait WeightInfo {
	fn register_identity() -> Weight;
	fn verify_identity() -> Weight;
	fn raise_dispute() -> Weight;
	fn vote_dispute() -> Weight;
}

/// Weights for pallet_proofofface using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ProofOfFace Identities (r:1 w:1)
	/// Proof: ProofOfFace Identities (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn register_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3593`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	
	/// Storage: ProofOfFace Identities (r:1 w:1)
	/// Proof: ProofOfFace Identities (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ProofOfFace Verifications (r:0 w:1)
	/// Proof: ProofOfFace Verifications (max_values: None, max_size: Some(256), added: 2731, mode: MaxEncodedLen)
	/// Storage: ProofOfFace VerificationCounter (r:1 w:1)
	/// Proof: ProofOfFace VerificationCounter (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn verify_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `7845`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 7845)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	
	/// Storage: ProofOfFace Identities (r:1 w:0)
	/// Proof: ProofOfFace Identities (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ProofOfFace DisputeCounter (r:1 w:1)
	/// Proof: ProofOfFace DisputeCounter (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: ProofOfFace Disputes (r:0 w:1)
	/// Proof: ProofOfFace Disputes (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
	fn raise_dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `6089`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 6089)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	
	/// Storage: ProofOfFace Disputes (r:1 w:1)
	/// Proof: ProofOfFace Disputes (max_values: None, max_size: Some(512), added: 2987, mode: MaxEncodedLen)
	/// Storage: ProofOfFace Identities (r:1 w:1)
	/// Proof: ProofOfFace Identities (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn vote_dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `280`
		//  Estimated: `5590`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 5590)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn register_identity() -> Weight {
		Weight::from_parts(16_000_000, 3593)
	}
	fn verify_identity() -> Weight {
		Weight::from_parts(26_000_000, 7845)
	}
	fn raise_dispute() -> Weight {
		Weight::from_parts(21_000_000, 6089)
	}
	fn vote_dispute() -> Weight {
		Weight::from_parts(19_000_000, 5590)
	}
}